---
# Auto release
- name: patch
  color: "5D3FD3"
- name: minor
  color: "5D3FD3"
- name: major
  color: "5D3FD3"
# Area
- name: area/ci
  color: "72ccf3"
- name: area/docs
  color: "72ccf3"
- name: area/script
  color: "72ccf3"
- name: area/docker
  color: "#72ccf3"
# Renovate
- name: renovate/image-release
  color: "ffc300"
# Semantic Type
- name: dependency/patch
  color: "FFEC19"
- name: dependency/minor
  color: "FF9800"
- name: dependency/major
  color: "F6412D"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: question
  color: "cc317c"
